# Generated by Django 4.2.5 on 2023-10-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcircle',
            name='created_at',
        ),
    ]
