# Generated by Django 4.2.5 on 2023-10-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0002_remove_historicalcircle_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkpi',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCircle',
        ),
        migrations.DeleteModel(
            name='HistoricalKpi',
        ),
    ]
