# Generated by Django 4.2.5 on 2023-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0004_historicalkpi_historicalcircle'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkpi',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalkpi',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
